[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0",
            "numpy", "cython", "extension-helpers"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pyregion/_version.py"
